"""initial

Revision ID: fbedd126777b
Revises: 
Create Date: 2026-06-18 17:54:59.863713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbedd126777b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'user', ['login'])
    op.add_column('wallet', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'wallet', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.drop_column('wallet', 'user_id')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'login')
    # ### end Alembic commands ###
